import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    appName: "SportHub",
    feed: "Feed",
    explore: "Explore",
    messages: "Messages",
    advice: "Advice",
    profile: "Profile",
    post: "Post",
    createPost: "Create Post",
    yourSportsFeed: "Your Sports Feed",
    discoverTraining: "Discover training, highlights, and motivation from athletes worldwide.",
    noPosts: "No posts yet",
    beFirst: "Be the first to share something!",
    searchPlaceholder: "Search by name, sport, or team...",
    discoverAthletes: "Discover Athletes",
    discoverDesc: "Discover coaches, athletes, and trainers across all sports",
    noProfilesFound: "No profiles found",
    mySportProfiles: "My Sport Profiles",
    addSport: "Add Sport",
    myPosts: "My Posts",
    logout: "Logout",
    message: "Message",
    askAdvice: "Ask Advice",
    sendRequest: "Send Request",
    posts: "Posts",
    backToExplore: "Back to Explore",
    selectConversation: "Select a conversation",
    typeMessage: "Type a message...",
    noConversations: "No conversations yet",
    adviceHub: "Advice Hub",
    requestExpertise: "Request and share sports expertise",
    received: "Received",
    sent: "Sent",
    noAdviceReceived: "No advice requests received yet",
    noAdviceSent: "You haven't sent any advice requests yet",
    reply: "Reply",
    accept: "Accept",
    decline: "Decline",
    publish: "Publish Post",
    sharePrompt: "Share your training, highlight, or motivation...",
    selectSport: "Select sport",
    selectType: "Select type",
    photo: "Photo",
    video: "Video",
    all: "All",
    loading: "Loading...",
  },
  es: {
    appName: "SportHub",
    feed: "Feed",
    explore: "Explorar",
    messages: "Mensajes",
    advice: "Consejos",
    profile: "Perfil",
    post: "Publicar",
    createPost: "Crear Publicación",
    yourSportsFeed: "Tu Feed Deportivo",
    discoverTraining: "Descubre entrenamientos, highlights y motivación de atletas de todo el mundo.",
    noPosts: "Aún no hay publicaciones",
    beFirst: "¡Sé el primero en compartir algo!",
    searchPlaceholder: "Buscar por nombre, deporte o equipo...",
    discoverAthletes: "Descubre Atletas",
    discoverDesc: "Descubre entrenadores, atletas e instructores en todos los deportes",
    noProfilesFound: "No se encontraron perfiles",
    mySportProfiles: "Mis Perfiles Deportivos",
    addSport: "Agregar Deporte",
    myPosts: "Mis Publicaciones",
    logout: "Cerrar Sesión",
    message: "Mensaje",
    askAdvice: "Pedir Consejo",
    sendRequest: "Enviar Solicitud",
    posts: "Publicaciones",
    backToExplore: "Volver a Explorar",
    selectConversation: "Selecciona una conversación",
    typeMessage: "Escribe un mensaje...",
    noConversations: "Aún no hay conversaciones",
    adviceHub: "Centro de Consejos",
    requestExpertise: "Solicita y comparte experiencia deportiva",
    received: "Recibidos",
    sent: "Enviados",
    noAdviceReceived: "Aún no has recibido solicitudes de consejo",
    noAdviceSent: "Aún no has enviado solicitudes de consejo",
    reply: "Responder",
    accept: "Aceptar",
    decline: "Rechazar",
    publish: "Publicar",
    sharePrompt: "Comparte tu entrenamiento, highlight o motivación...",
    selectSport: "Seleccionar deporte",
    selectType: "Seleccionar tipo",
    photo: "Foto",
    video: "Video",
    all: "Todos",
    loading: "Cargando...",
  },
  fr: {
    appName: "SportHub",
    feed: "Fil",
    explore: "Explorer",
    messages: "Messages",
    advice: "Conseils",
    profile: "Profil",
    post: "Publier",
    createPost: "Créer une Publication",
    yourSportsFeed: "Votre Fil Sportif",
    discoverTraining: "Découvrez l'entraînement, les moments forts et la motivation d'athlètes du monde entier.",
    noPosts: "Pas encore de publications",
    beFirst: "Soyez le premier à partager quelque chose!",
    searchPlaceholder: "Rechercher par nom, sport ou équipe...",
    discoverAthletes: "Découvrir les Athlètes",
    discoverDesc: "Découvrez des entraîneurs, des athlètes et des formateurs dans tous les sports",
    noProfilesFound: "Aucun profil trouvé",
    mySportProfiles: "Mes Profils Sportifs",
    addSport: "Ajouter un Sport",
    myPosts: "Mes Publications",
    logout: "Déconnexion",
    message: "Message",
    askAdvice: "Demander Conseil",
    sendRequest: "Envoyer la Demande",
    posts: "Publications",
    backToExplore: "Retour à Explorer",
    selectConversation: "Sélectionner une conversation",
    typeMessage: "Tapez un message...",
    noConversations: "Pas encore de conversations",
    adviceHub: "Centre de Conseils",
    requestExpertise: "Demandez et partagez l'expertise sportive",
    received: "Reçus",
    sent: "Envoyés",
    noAdviceReceived: "Aucune demande de conseil reçue",
    noAdviceSent: "Vous n'avez envoyé aucune demande de conseil",
    reply: "Répondre",
    accept: "Accepter",
    decline: "Refuser",
    publish: "Publier",
    sharePrompt: "Partagez votre entraînement, highlight ou motivation...",
    selectSport: "Sélectionner le sport",
    selectType: "Sélectionner le type",
    photo: "Photo",
    video: "Vidéo",
    all: "Tous",
    loading: "Chargement...",
  },
  de: {
    appName: "SportHub",
    feed: "Feed",
    explore: "Entdecken",
    messages: "Nachrichten",
    advice: "Ratschläge",
    profile: "Profil",
    post: "Posten",
    createPost: "Beitrag Erstellen",
    yourSportsFeed: "Dein Sport-Feed",
    discoverTraining: "Entdecke Training, Highlights und Motivation von Athleten weltweit.",
    noPosts: "Noch keine Beiträge",
    beFirst: "Sei der Erste, der etwas teilt!",
    searchPlaceholder: "Nach Name, Sport oder Team suchen...",
    discoverAthletes: "Athleten Entdecken",
    discoverDesc: "Entdecke Trainer, Athleten und Coaches in allen Sportarten",
    noProfilesFound: "Keine Profile gefunden",
    mySportProfiles: "Meine Sport-Profile",
    addSport: "Sport Hinzufügen",
    myPosts: "Meine Beiträge",
    logout: "Abmelden",
    message: "Nachricht",
    askAdvice: "Rat Fragen",
    sendRequest: "Anfrage Senden",
    posts: "Beiträge",
    backToExplore: "Zurück zu Entdecken",
    selectConversation: "Wähle eine Unterhaltung",
    typeMessage: "Nachricht eingeben...",
    noConversations: "Noch keine Unterhaltungen",
    adviceHub: "Ratgeber-Hub",
    requestExpertise: "Frage und teile Sport-Expertise",
    received: "Empfangen",
    sent: "Gesendet",
    noAdviceReceived: "Noch keine Ratschlag-Anfragen erhalten",
    noAdviceSent: "Du hast noch keine Ratschlag-Anfragen gesendet",
    reply: "Antworten",
    accept: "Akzeptieren",
    decline: "Ablehnen",
    publish: "Veröffentlichen",
    sharePrompt: "Teile dein Training, Highlight oder Motivation...",
    selectSport: "Sport auswählen",
    selectType: "Typ auswählen",
    photo: "Foto",
    video: "Video",
    all: "Alle",
    loading: "Laden...",
  },
  pt: {
    appName: "SportHub",
    feed: "Feed",
    explore: "Explorar",
    messages: "Mensagens",
    advice: "Conselhos",
    profile: "Perfil",
    post: "Publicar",
    createPost: "Criar Publicação",
    yourSportsFeed: "Seu Feed Esportivo",
    discoverTraining: "Descubra treinos, destaques e motivação de atletas do mundo todo.",
    noPosts: "Ainda não há publicações",
    beFirst: "Seja o primeiro a compartilhar algo!",
    searchPlaceholder: "Pesquisar por nome, esporte ou time...",
    discoverAthletes: "Descobrir Atletas",
    discoverDesc: "Descubra treinadores, atletas e instrutores em todos os esportes",
    noProfilesFound: "Nenhum perfil encontrado",
    mySportProfiles: "Meus Perfis Esportivos",
    addSport: "Adicionar Esporte",
    myPosts: "Minhas Publicações",
    logout: "Sair",
    message: "Mensagem",
    askAdvice: "Pedir Conselho",
    sendRequest: "Enviar Pedido",
    posts: "Publicações",
    backToExplore: "Voltar para Explorar",
    selectConversation: "Selecione uma conversa",
    typeMessage: "Digite uma mensagem...",
    noConversations: "Ainda não há conversas",
    adviceHub: "Central de Conselhos",
    requestExpertise: "Solicite e compartilhe expertise esportiva",
    received: "Recebidos",
    sent: "Enviados",
    noAdviceReceived: "Nenhum pedido de conselho recebido ainda",
    noAdviceSent: "Você ainda não enviou pedidos de conselho",
    reply: "Responder",
    accept: "Aceitar",
    decline: "Recusar",
    publish: "Publicar",
    sharePrompt: "Compartilhe seu treino, destaque ou motivação...",
    selectSport: "Selecionar esporte",
    selectType: "Selecionar tipo",
    photo: "Foto",
    video: "Vídeo",
    all: "Todos",
    loading: "Carregando...",
  },
  zh: {
    appName: "SportHub",
    feed: "动态",
    explore: "探索",
    messages: "消息",
    advice: "建议",
    profile: "个人资料",
    post: "发布",
    createPost: "创建帖子",
    yourSportsFeed: "您的运动动态",
    discoverTraining: "发现来自世界各地运动员的训练、精彩瞬间和激励。",
    noPosts: "还没有帖子",
    beFirst: "成为第一个分享的人！",
    searchPlaceholder: "按姓名、运动或团队搜索...",
    discoverAthletes: "发现运动员",
    discoverDesc: "发现所有运动项目的教练、运动员和培训师",
    noProfilesFound: "未找到个人资料",
    mySportProfiles: "我的运动资料",
    addSport: "添加运动",
    myPosts: "我的帖子",
    logout: "退出",
    message: "消息",
    askAdvice: "请教",
    sendRequest: "发送请求",
    posts: "帖子",
    backToExplore: "返回探索",
    selectConversation: "选择对话",
    typeMessage: "输入消息...",
    noConversations: "还没有对话",
    adviceHub: "建议中心",
    requestExpertise: "请求和分享运动专业知识",
    received: "收到",
    sent: "已发送",
    noAdviceReceived: "还没有收到建议请求",
    noAdviceSent: "您还没有发送建议请求",
    reply: "回复",
    accept: "接受",
    decline: "拒绝",
    publish: "发布",
    sharePrompt: "分享您的训练、精彩瞬间或激励...",
    selectSport: "选择运动",
    selectType: "选择类型",
    photo: "照片",
    video: "视频",
    all: "全部",
    loading: "加载中...",
  },
  ja: {
    appName: "SportHub",
    feed: "フィード",
    explore: "探索",
    messages: "メッセージ",
    advice: "アドバイス",
    profile: "プロフィール",
    post: "投稿",
    createPost: "投稿を作成",
    yourSportsFeed: "あなたのスポーツフィード",
    discoverTraining: "世界中のアスリートからトレーニング、ハイライト、モチベーションを発見。",
    noPosts: "まだ投稿はありません",
    beFirst: "最初に共有しましょう！",
    searchPlaceholder: "名前、スポーツ、チームで検索...",
    discoverAthletes: "アスリートを探す",
    discoverDesc: "すべてのスポーツのコーチ、アスリート、トレーナーを発見",
    noProfilesFound: "プロフィールが見つかりません",
    mySportProfiles: "マイスポーツプロフィール",
    addSport: "スポーツを追加",
    myPosts: "マイ投稿",
    logout: "ログアウト",
    message: "メッセージ",
    askAdvice: "アドバイスを求める",
    sendRequest: "リクエストを送信",
    posts: "投稿",
    backToExplore: "探索に戻る",
    selectConversation: "会話を選択",
    typeMessage: "メッセージを入力...",
    noConversations: "まだ会話はありません",
    adviceHub: "アドバイスハブ",
    requestExpertise: "スポーツの専門知識をリクエストして共有",
    received: "受信",
    sent: "送信済み",
    noAdviceReceived: "まだアドバイスのリクエストは受け取っていません",
    noAdviceSent: "まだアドバイスのリクエストを送信していません",
    reply: "返信",
    accept: "承認",
    decline: "拒否",
    publish: "公開",
    sharePrompt: "トレーニング、ハイライト、モチベーションを共有...",
    selectSport: "スポーツを選択",
    selectType: "タイプを選択",
    photo: "写真",
    video: "ビデオ",
    all: "すべて",
    loading: "読み込み中...",
  },
  ar: {
    appName: "SportHub",
    feed: "الخلاصة",
    explore: "استكشاف",
    messages: "الرسائل",
    advice: "النصائح",
    profile: "الملف الشخصي",
    post: "نشر",
    createPost: "إنشاء منشور",
    yourSportsFeed: "خلاصتك الرياضية",
    discoverTraining: "اكتشف التدريب والإنجازات والتحفيز من رياضيين حول العالم.",
    noPosts: "لا توجد منشورات بعد",
    beFirst: "كن أول من يشارك شيئًا!",
    searchPlaceholder: "البحث بالاسم أو الرياضة أو الفريق...",
    discoverAthletes: "اكتشاف الرياضيين",
    discoverDesc: "اكتشف المدربين والرياضيين والمدربين في جميع الرياضات",
    noProfilesFound: "لم يتم العثور على ملفات شخصية",
    mySportProfiles: "ملفاتي الرياضية",
    addSport: "إضافة رياضة",
    myPosts: "منشوراتي",
    logout: "تسجيل الخروج",
    message: "رسالة",
    askAdvice: "اطلب نصيحة",
    sendRequest: "إرسال طلب",
    posts: "المنشورات",
    backToExplore: "العودة إلى الاستكشاف",
    selectConversation: "اختر محادثة",
    typeMessage: "اكتب رسالة...",
    noConversations: "لا توجد محادثات بعد",
    adviceHub: "مركز النصائح",
    requestExpertise: "اطلب وشارك الخبرة الرياضية",
    received: "الواردة",
    sent: "المرسلة",
    noAdviceReceived: "لم تتلق طلبات نصيحة بعد",
    noAdviceSent: "لم ترسل طلبات نصيحة بعد",
    reply: "رد",
    accept: "قبول",
    decline: "رفض",
    publish: "نشر",
    sharePrompt: "شارك تدريبك أو إنجازك أو تحفيزك...",
    selectSport: "اختر الرياضة",
    selectType: "اختر النوع",
    photo: "صورة",
    video: "فيديو",
    all: "الكل",
    loading: "جاري التحميل...",
  },
  hi: {
    appName: "SportHub",
    feed: "फ़ीड",
    explore: "अन्वेषण करें",
    messages: "संदेश",
    advice: "सलाह",
    profile: "प्रोफ़ाइल",
    post: "पोस्ट",
    createPost: "पोस्ट बनाएं",
    yourSportsFeed: "आपका स्पोर्ट्स फ़ीड",
    discoverTraining: "दुनिया भर के एथलीटों से ट्रेनिंग, हाइलाइट्स और प्रेरणा खोजें।",
    noPosts: "अभी तक कोई पोस्ट नहीं",
    beFirst: "कुछ साझा करने वाले पहले व्यक्ति बनें!",
    searchPlaceholder: "नाम, खेल या टीम से खोजें...",
    discoverAthletes: "एथलीट खोजें",
    discoverDesc: "सभी खेलों में कोच, एथलीट और प्रशिक्षक खोजें",
    noProfilesFound: "कोई प्रोफाइल नहीं मिली",
    mySportProfiles: "मेरी स्पोर्ट्स प्रोफाइल",
    addSport: "खेल जोड़ें",
    myPosts: "मेरी पोस्ट",
    logout: "लॉग आउट",
    message: "संदेश",
    askAdvice: "सलाह मांगें",
    sendRequest: "अनुरोध भेजें",
    posts: "पोस्ट",
    backToExplore: "अन्वेषण पर वापस जाएं",
    selectConversation: "बातचीत चुनें",
    typeMessage: "संदेश टाइप करें...",
    noConversations: "अभी तक कोई बातचीत नहीं",
    adviceHub: "सलाह केंद्र",
    requestExpertise: "खेल विशेषज्ञता का अनुरोध करें और साझा करें",
    received: "प्राप्त",
    sent: "भेजा गया",
    noAdviceReceived: "अभी तक कोई सलाह अनुरोध प्राप्त नहीं हुआ",
    noAdviceSent: "आपने अभी तक कोई सलाह अनुरोध नहीं भेजा",
    reply: "जवाब दें",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    publish: "प्रकाशित करें",
    sharePrompt: "अपनी ट्रेनिंग, हाइलाइट या प्रेरणा साझा करें...",
    selectSport: "खेल चुनें",
    selectType: "प्रकार चुनें",
    photo: "फोटो",
    video: "वीडियो",
    all: "सभी",
    loading: "लोड हो रहा है...",
  },
  ru: {
    appName: "SportHub",
    feed: "Лента",
    explore: "Обзор",
    messages: "Сообщения",
    advice: "Советы",
    profile: "Профиль",
    post: "Опубликовать",
    createPost: "Создать пост",
    yourSportsFeed: "Ваша спортивная лента",
    discoverTraining: "Откройте для себя тренировки, лучшие моменты и мотивацию от спортсменов со всего мира.",
    noPosts: "Пока нет постов",
    beFirst: "Будьте первым, кто поделится чем-то!",
    searchPlaceholder: "Поиск по имени, спорту или команде...",
    discoverAthletes: "Найти спортсменов",
    discoverDesc: "Найдите тренеров, спортсменов и инструкторов во всех видах спорта",
    noProfilesFound: "Профили не найдены",
    mySportProfiles: "Мои спортивные профили",
    addSport: "Добавить спорт",
    myPosts: "Мои посты",
    logout: "Выйти",
    message: "Сообщение",
    askAdvice: "Попросить совет",
    sendRequest: "Отправить запрос",
    posts: "Посты",
    backToExplore: "Вернуться к обзору",
    selectConversation: "Выберите беседу",
    typeMessage: "Введите сообщение...",
    noConversations: "Пока нет бесед",
    adviceHub: "Центр советов",
    requestExpertise: "Запросите и поделитесь спортивным опытом",
    received: "Получено",
    sent: "Отправлено",
    noAdviceReceived: "Запросы на советы еще не получены",
    noAdviceSent: "Вы еще не отправили запросы на советы",
    reply: "Ответить",
    accept: "Принять",
    decline: "Отклонить",
    publish: "Опубликовать",
    sharePrompt: "Поделитесь своей тренировкой, достижением или мотивацией...",
    selectSport: "Выберите спорт",
    selectType: "Выберите тип",
    photo: "Фото",
    video: "Видео",
    all: "Все",
    loading: "Загрузка...",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("sporthub_language");
    return saved || navigator.language.split("-")[0] || "en";
  });

  useEffect(() => {
    localStorage.setItem("sporthub_language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};